language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jotathebest
  password:
    secure: FiwzVon1dWnuohA4tNinRxEhwEmU3hs0ntBe/s99hha/rXdVmfGuaMQLbNDBrcmOQnzNfge5pZRi3b1zp+ac0CSqWLu754AzRhS+UhQ9f0dm8Vm+aGryVLqu/mw4S6+luhbGhtTlD/sj8CHSUHmAkQmHCZYSc41x817D6darOqA9egYLFJNjom/+GCZNGl+Z7z7dbUYoOFpWc7J2dFKRVuF/wTOf55mALbjghIaMEQyy2wXr7rtxda6aSORC1DEsQWc/6So8iLj9gCDH3P2h6WRNIs6k49h0Ul7ztjRfOObC4nUEznWEJbH69cR1dfT67NvwSEgnR6SR1afITzEulanFnI2rwvBoYMll1UNiBUAZ0IoyLCiU8jKqVgTYxy5OaLb4EaaiQ8D7kbgnYKfyMXKDDnQ9CocRL1JeQB4XCiQoVQi7e10ocgVsUAiDs7t03TB4zbg1jlW9VZFLTHXAOEe2fvqmG6tSMKxFv4zKka0ewHdPWMKu4J5M2oqqVvVrgeWOucAaYah5GEGEUWITeY42vkQnyC+hbXqx/AVqgY90bZLCN4QAURTRtVezXrAkhT0meTfY3jtkExuoKCoD+in0LilyzV58xTRvkMPgjwRoudPeHGAq5xyX9lMGo0rJ9DsLbWh9Z0oeb+ZnI7oXu0DtHb/zcJB53QVUTmGZBn4=
  on:
    tags: true
    repo: jotathebest/websiteTest
    python: 3.6
